on:
  push:
    branches:
      - main

jobs:
  build-test-and-quality:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore --verbosity normal
    - name: Test
      run: dotnet test --no-restore --verbosity normal

